development:
  # adapter: 'mysql2'
  # host: "localhost"
  # database: "angular.example.app"
  # username: 'root'
  # password: ''
  # poot: 128
  # encoding: utf8
  adapter: 'sqlite3'
  database: 'data/dev.database.db'

test:
  adapter: 'sqlite3'
  database: 'data/test.database.db'

production:
  #nothing